#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

if (PHP_MAJOR_VERSION < 8) {
    echo "PHP Version Mismatch\n";
    exit(130);
}

define('LARAVEL_START', (new DateTime)->format('U.u'));

require __DIR__ . '/vendor/autoload.php';
/** @var Application $app */
$app = require_once __DIR__ . '/bootstrap/app.php';
$status = $app->handleCommand(new ArgvInput);
exit($status);
